filter:
    paths: ["src/*"]
    excluded_paths:
        - "src/*Bundle/Tests/"

checks:
    php:
        code_rating: true
        duplication: false
        excluded_dependencies:
            - npm-asset/marked
            - npm-asset/markdown-it-underline
            - npm-asset/github-markdown-css
