_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt
    schemes:  ['%httpProtocol%']

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
    schemes:  ['%httpProtocol%']

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error
    schemes:  ['%httpProtocol%']

_main:
    resource: routing.yml
    schemes:  ['%httpProtocol%']
