github_files:
    resource: "@GithubFilesBundle/Controller/"
    type:     annotation
    prefix:   /

salt_user:
    resource: "@SaltUserBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_util:
    resource: "@CftfUtilBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_cms:
    resource: "@CftfCmsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_sbac:
    resource: "@CftfSbacBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_ims:
    resource: "@CftfImsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_asn:
    resource: "@CftfAsnBundle/Controller/"
    type:     annotation
    prefix:   /

cftf:
    resource: "@CftfBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    path: /logout

