salt_user:
    resource: "@SaltUserBundle/Controller/"
    type:     annotation
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

cftf_util:
    resource: "@CftfUtilBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_cms:
    resource: "@CftfCmsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_sbac:
    resource: "@CftfSbacBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_ims:
    resource: "@CftfImsBundle/Controller/"
    type:     annotation
    prefix:   /

cftf_asn:
    resource: "@CftfAsnBundle/Controller/"
    type:     annotation
    prefix:   /

cftf:
    resource: "@CftfBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    path: /logout

