# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    google.preauth_subscriber:
#        class: Pcg\GoogleBundle\Listener\ConnectPreAuthListener
#        arguments: ["@twig"]
#        tags:
#            - { name: kernel.event_subscriber }

    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $rootDir: "%kernel.root_dir%"
            $mailFromEmail: '%mail_feature_from_email%'
            $externalDocCache: '@salt.cache.external_docs'
            $firebasePrefix: '%firebase_prefix%'

    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/{Console,Handler,Form/Type,EventListener,Service,Repository,Security,Twig}'

    App\Controller\User\OAuthServiceController:
        arguments:
            $githubClientId: '%github_client_id%'
            $githubClientSecret: '%github_client_secret%'
            $githubRedirectUri: "@=container.hasParameter('github_redirect_uri') ? parameter('github_redirect_uri') : null"

    App\Controller\Framework\LsDocController:
        arguments:
            $guzzleJsonClient: '@csa_guzzle.client.json'

    App\Controller\Framework\DocTreeController:
        arguments:
            $guzzleJsonClient: '@csa_guzzle.client.json'

    App\Controller\User\SignupController:
        arguments:
            $kernelEnv: '%kernel.environment%'

    App\EventListener\LoginListener:
        class: App\EventListener\LoginListener
        arguments:
            $captchaSecret: '%google_captcha_secret_key%'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }


    # Workarounds for 3.4 deprecations
    Symfony\Bundle\SwiftmailerBundle\Command\:
        resource: '../../vendor/symfony/swiftmailer-bundle/Command'
        tags: ['console.command']

    Symfony\Bundle\AsseticBundle\Command\:
        resource: '../../vendor/symfony/assetic-bundle/Command'
        tags: ['console.command']


    # Aliased services
    Qandidate\Toggle\ToggleManager: '@qandidate.toggle.manager'
    Qandidate\Toggle\ContextFactory: '@qandidate.toggle.user_context_factory'
    GuzzleHttp\ClientInterface: '@csa_guzzle.client.json'
    SimpleThings\EntityAudit\AuditReader: '@simplethings_entityaudit.reader'

    # Manual services
    Kreait\Firebase:
        factory: 'App\Service\FirebaseFactory:createFirebase'
        arguments:
            $logger: '@logger'
            $projectId: '%firebase_project_id%'
            $clientId: '%firebase_client_id%'
            $clientEmail: '%firebase_client_email%'
            $privateKey: '%firebase_private_key%'
            $dbUri: '%firebase_db_url%'

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            $pdoOrDsn: 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            $options: { db_username: '%database_user%', db_password: '%database_password%', db_table: 'auth_session', db_id_col: 'id', db_connection_options: "%pdo_options%" }

    salt.cache.external_docs:
        class: Symfony\Component\Cache\Adapter\PdoAdapter
        arguments:
            $connOrDsn: '@doctrine.dbal.default_connection'
            $namespace: 'externalDoc-'
            $defaultLifetime: 0
