# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    google.preauth_subscriber:
#        class: Pcg\GoogleBundle\Listener\ConnectPreAuthListener
#        arguments: ["@twig"]
#        tags:
#            - { name: kernel.event_subscriber }

    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        #public: false

    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/App/{Console,Handler,Form/Type,Service,Repository}'

    App\Controller\:
        resource: '../../src/App/Controller'
        public: true
        tags: ['controller.service_arguments']

    App\Controller\Site\AboutController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $rootDir: '%kernel.root_dir%'

    App\Console\ClearFirebaseNotificationsCommand:
        public: true
        arguments:
            - '@Kreait\Firebase'
            - '%firebase_prefix%'

    App\Handler\Email\:
        resource: '../../src/App/Handler/Email'
        public: true
        arguments:
            # Move to _defaults: bind: in Symfony 3.4
            $mailFromEmail: '%mail_feature_from_email%'

    # Autowiring commands
    CftfBundle\Command\:
        resource: '../../src/CftfBundle/Command'
        tags: ['console.command']

    CftfBundle\Service\:
        resource: '../../src/CftfBundle/Service'


    # Workarounds for 3.4 deprecations
    Symfony\Bundle\SwiftmailerBundle\Command\:
        resource: '../../vendor/symfony/swiftmailer-bundle/Command'
        tags: ['console.command']

    Sensio\Bundle\GeneratorBundle\Command\:
        resource: '../../vendor/sensio/generator-bundle/Command/*Command.php'
        tags: ['console.command']

    Symfony\Bundle\AsseticBundle\Command\:
        resource: '../../vendor/symfony/assetic-bundle/Command'
        tags: ['console.command']


    # Aliased services
    Qandidate\Toggle\ToggleManager: '@qandidate.toggle.manager'
    Qandidate\Toggle\ContextFactory: '@qandidate.toggle.user_context_factory'
    GuzzleHttp\ClientInterface: '@csa_guzzle.client.json'
    SimpleThings\EntityAudit\AuditReader: '@simplethings_entityaudit.reader'

    # Manual services
    Kreait\Firebase:
        factory: 'App\Service\FirebaseFactory:createFirebase'
        arguments:
            - '@logger'
            - '%firebase_project_id%'
            - '%firebase_client_id%'
            - '%firebase_client_email%'
            - '%firebase_private_key%'
            - '%firebase_db_url%'

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%', db_table: 'auth_session', db_id_col: 'id', db_connection_options: "%pdo_options%" }

    salt.cache.external_docs:
        class: Symfony\Component\Cache\Adapter\PdoAdapter
        public: true
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'externalDoc-'
            - 0

    App\EventListener\LoginListener:
        class: App\EventListener\LoginListener
        arguments:
            $captchaSecret: '%google_captcha_secret_key%'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
