services:
    salt.authentication.json_form_entry_point:
        class: App\Security\EntryPoint\JsonFormAuthenticationEntryPoint
        parent: security.authentication.form_entry_point.main
        autowire: true
        public: true
