version: '2'
services:
  # Tools used
  # the docker-compose format does not have a way to specify not to run these upon "up"
  # so we set to command to /bin/true to exit right away
  phpcli:
    #build:
    #  context: ./php
    image: opensalt/php:7.1.0RC6-cli
    environment:
      SYMFONY__MYSQL__DATABASE: "${MYSQL_DATABASE}"
      SYMFONY__MYSQL__USER: "${MYSQL_USER}"
      SYMFONY__MYSQL__PASSWORD: "${MYSQL_PASSWORD}"
      SYMFONY__MYSQL__HOST: "db"
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST: "db"
    volumes:
      - &project_root "..:/var/www/html"
    working_dir: /var/www/html
    command: [ /bin/true ]

  composer:
    #build:
    #  context: ./composer
    image: opensalt/composer:latest
    environment:
      SYMFONY__MYSQL__DATABASE: "${MYSQL_DATABASE}"
      SYMFONY__MYSQL__USER: "${MYSQL_USER}"
      SYMFONY__MYSQL__PASSWORD: "${MYSQL_PASSWORD}"
      SYMFONY__MYSQL__HOST: "db"
    volumes:
      - *project_root
      - ./data/composer/slash:/composer
      - ./data/composer/root-user:/root/composer
      - ./data/composer/passwd.tmp:/etc/passwd
    working_dir: /var/www/html
    command: [ "-q" ]

  gulp:
    #build:
    #  context: ./gulp
    image: opensalt/gulp:latest
    volumes:
      - "..:/build/app"

#volumes:
