lightsaml_sp:
    resource: "@LightSamlSpBundle/Resources/config/routing.yml"
    prefix: saml

logout:
    path: /logout

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
